server:
  ip: 0.0.0.0
  port: 8083
  name: stock-srv
  tags:
    - stock
    - grpc
  external_ip: 192.168.5.177
  debug: true
mysql:
  addr: ubuntu-learn:3306
  user: root
  password: Albelt2017Go
  db: mxshop_srvs
  slow_threshold: 2
redis:
  addr: ubuntu-learn:6379
  password: Albelt2017Go
  db: 10
consul:
  addr: ubuntu-learn:8500
  health_check:
    interval: 10s
    timeout: 5s
    deregister: 1m
rocket_mq:
  name_server: 192.168.5.199:9876
  topic: order_create
  consumer_group_name: stock_srv_consumer